# Generated by Django 3.2.5 on 2021-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=30)),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('freq', models.FloatField()),
            ],
        ),
    ]
