# Generated by Django 3.2.5 on 2021-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='tf_idf',
            field=models.FloatField(default=0),
        ),
    ]
