# Generated by Django 3.2.5 on 2021-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_count_tf_idf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
